services:

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ./mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception
  
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html/wordpress
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    networks:
      - inception
    restart: always
  
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./wordpress_data:/var/www/html/wordpress
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception


networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind  
      device: /workspaces/inception/srcs/mariadb_data
  wordpress_data:
    driver_opts:
      type: none
      o : bind
      device : /workspaces/inception/srcs/wordpress_data
