version: "2.0" 

services:

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb 
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception
  
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - ./wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
  
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception


networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local  # May be implicit in older versions
    driver_opts:
      type: none  # Default for bind mounts
      o: bind  # Corrected typo (option for bind mount)
      device: /home/ubuntu/inception/inception/srcs/mariadb_data
  wordpress_data:
    driver_opts:
      type: none
      o : bind
      device : /home/ubuntu/inception/inception/srcs/wordpress_data
