services:

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb:1337
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env
  
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    image: wordpress:1337
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    env_file:
      - .env
  
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx:1337
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception


networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind  
      device: /home/gothmane/data/mariadb/
  wordpress:
    driver_opts:
      type: none
      o : bind
      device : /home/gothmane/data/wordpress/
